### PR TITLE
Update to replace deprecated call with yo hubot generator instead.

### PR DESCRIPTION
**Pull request by truongvo**
I started changing the Docker file to and realize you already did the complicated magic needed there. Thanks

Signed-off-by: Truong Vo <tronvo@gmail.com>

### CODE REVIEW

**Comment by rothgar** [comment]
Is there a way to pass --adapter= to the yo command from the gui so the bot is created with the correct adapter too?

**Comment by truongvo** [comment]
Yeah, that should be easy assuming yo does the right thing with --adapter
and defaults.  I thought you said defaults work as the UI manages it.  What
about the other parameters?

On Thu, Mar 5, 2015 at 2:03 PM, Justin Garrison <notifications@github.com>
wrote:

> Is there a way to pass --adapter= to the yo command from the gui so the
> bot is created with the correct adapter too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rothgar/hubot-control/pull/1#issuecomment-77461945>.
>



-- 
Truong Vo

**Comment by rothgar** [comment]
I have tested with
```
yo hubot --adapter=slack --defaults
```
and that works as expected. The problem with only specifying `--defaults` is the adapter doesn't become part of the package.json so the first time the application is started it complains about not having an adapter (or using campfire by default). You can manually put the adapter in the package.json definition but it's a required field when creating a bot so we might as well use it.
The other parameters like `--user` `--description` etc. aren't exposed in the gui when creating a bot so they don't matter as much. I also think they might be adapter specific. For example, you can specify `--name` but if you're using slack the name is overridden by the slack API key.

**Comment by truongvo** [comment]
I've made the change.  Quick test from web app seems to work, though I'm still figuring out how to use this thing :)

**Comment by rothgar** [comment]
I tested this with a new container and it appears the `mkdir -p` command fails although I'm not sure why because permissions look correct. After the directory creation fails the `yo hubot` command obviously fails too.

**Comment by truongvo** [comment]
So I rebuilt my container and ran against the rails app started by unicorn (before I was testing by going running bash in the container and starting a development server).  It seems to work fine when creating the bot.  I'll send you the url to play with.

Before I mentioned I thought it was a relative directory issue, but the code is using the full absolute path that it was previously using to cd into the directory.

There is a difference with my container though in that I'm using sqlite and added running db:migrate in the docker file, but I don't think that would make a difference.  We'll have to poke around some more.  I wonder if it's related at all to the permissions issues earlier with your container.  I'll send you my environment info.

**Pull request closed without merging**
